version: '3'

# development

services:
  back:
    container_name: chouquette-back
    volumes:
      - ./back:/chouquette
    working_dir: /chouquette
    entrypoint: sbt
    stdin_open: true
    tty: true

  front:
    container_name: chouquette-front
    volumes:
      - ./front:/chouquette
    working_dir: /chouquette
    entrypoint: bash
    stdin_open: true
    tty: true
