version: '3'

# production

networks:
  chouquette:
    ipam:
      config:
        - subnet: 10.42.96.0/24

services:
  back:
    build: ./back
    image: chouquette-back:latest
    hostname: chouquette-back
    networks:
      - chouquette
    ports:
      - 51264:9000

  front:
    build: ./front
    image: chouquette-front:latest
    hostname: chouquette-front
    networks:
      - chouquette
    ports:
      - 51265:8080
